# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: 'main'
  pull_request:
    branches: '**'

jobs:
  publish-release:
    strategy:
      fail-fast: false
      matrix:
        rid: ['win-x64']
        project: ['Assembler', 'Emulator', 'InstructionTable', 'Linker', 'Tools']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Publish
        run: |
          dotnet publish ${{ matrix.project }}/${{ matrix.project }}.csproj --configuration Debug --runtime ${{ matrix.rid }} --output ./publish_${{ matrix.rid }}_${{ matrix.project }} --self-contained false --framework net452
      - name: Create README.txt
        run: |
          echo "Привет! Чтобы запустить програму, установите .NET Framework 4.5.2" > ./publish_${{ matrix.rid }}_${{ matrix.project }}/README.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project }}-${{ matrix.rid }}-build
          path: ./publish_${{ matrix.rid }}_${{ matrix.project }}
